// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCharacterAPI.Data;

namespace MovieCharacterAPI.Migrations
{
    [DbContext(typeof(MovieCharacterAPIDbContext))]
    [Migration("20220228073248_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "CharactersId");

                    b.HasIndex("CharactersId");

                    b.ToTable("CharacterMovie");

                    b.HasData(
                        new
                        {
                            MoviesId = 1,
                            CharactersId = 1
                        },
                        new
                        {
                            MoviesId = 2,
                            CharactersId = 2
                        },
                        new
                        {
                            MoviesId = 3,
                            CharactersId = 3
                        },
                        new
                        {
                            MoviesId = 4,
                            CharactersId = 3
                        });
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CharacterPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Iron man",
                            CharacterPicture = "https://th.bing.com/th/id/R.a1493b8983c19f3158df354f1c0fe054?rik=t6iG5uRzMhaPjw&pid=ImgRaw&r=0",
                            FullName = "Robert Downey Jr",
                            Gender = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Frodo Baggins",
                            CharacterPicture = "https://i.pinimg.com/736x/1b/93/84/1b9384b6de87ab45a1391d454bd695c5.jpg",
                            FullName = "Elijah Wood",
                            Gender = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "James Bond",
                            CharacterPicture = "https://assets.mi6-hq.com/images/features/magazine-special4a.jpg",
                            FullName = "Roger Moore",
                            Gender = "Male"
                        });
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The films based on characters that appear in comic books published by Marvel Comics",
                            Name = "Marvel cinematic universe"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fantasy films based on the novel written by J.R.R. Tolkien",
                            Name = "The lord of the rings"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A british secret agent working for MI6 under the codename 007",
                            Name = "James Bond"
                        });
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("MoviePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReleaseYear")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Jon Favreau",
                            FranchiseId = 1,
                            Genre = "Action",
                            MoviePicture = "https://th.bing.com/th/id/R.dc6072bd82f5c534f7f7583f451a5534?rik=GqOVQyAWzMtbcw&pid=ImgRaw&r=0",
                            MovieTitle = "Iron man",
                            ReleaseYear = "2008",
                            Trailer = "https://www.youtube.com/watch?v=8ugaeA-nMTc"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Peter Jackson",
                            FranchiseId = 2,
                            Genre = "Fantasy",
                            MoviePicture = "https://th.bing.com/th/id/OIP.iu0nj0wNpcI0N-Pss_ihwQHaKw?pid=ImgDet&rs=1",
                            MovieTitle = "The fellowship of the ring",
                            ReleaseYear = "2001",
                            Trailer = "https://www.youtube.com/watch?v=V75dMMIW2B4"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Lewis Gilbert",
                            FranchiseId = 3,
                            Genre = "Action",
                            MoviePicture = "https://th.bing.com/th/id/R.769e22f0f07bc67a3a5430a88d10dbd6?rik=eZJtqpB1%2b3MaJA&pid=ImgRaw&r=0",
                            MovieTitle = "Moonraker",
                            ReleaseYear = "1979",
                            Trailer = "https://www.youtube.com/watch?v=KFOOjYU16KE"
                        },
                        new
                        {
                            Id = 4,
                            Director = "John Glen",
                            FranchiseId = 3,
                            Genre = "Action",
                            MoviePicture = "https://i.pinimg.com/originals/79/b4/9b/79b49b9b10c0cf4c472167c60d65cd43.jpg",
                            MovieTitle = "Octopussy",
                            ReleaseYear = "1983",
                            Trailer = "https://www.youtube.com/watch?v=q1hLWZzgZvU"
                        });
                });

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.HasOne("MovieCharacterAPI.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCharacterAPI.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Movie", b =>
                {
                    b.HasOne("MovieCharacterAPI.Models.Franchise", "Franchise")
                        .WithMany("Movies")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Franchise", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
